#!/bin/bash

## Load the config file
CFDIRG="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
source "${CFDIRG}/config"

## QEMU (VM) command
qemu-system-x86_64 -vga std -display sdl \
  -m "${RAM}"M -rtc clock=host,base=localtime \
  -device sb16 -boot order=d \
  -drive file="${DUMMY_IMG}" \
  -cdrom "${DUMMY_ISO}" >> ${LOG} 2>&1 &
  
# To use floppy Disk use "-fda /path/to/the/image.img
